language: node_js
notifications:
  email: false
  slack:
    rooms:
      secure: LLIuCOqOB0GLiyyV/L+NPErpAM4T3DuZQKa9v08R2nqQZ/53uUnNg25/4hzjnVoBNtJGrfdWKLjx4Ddgox4h97oD2aos8xLyuQXEp+S3rVPc02fTilU4HRrMoxbl4qzvAjhQlwSLaCva1xQJ9RRgTUkz22azt3MAkwe/eUtyUSq3A2BJi/pVBW0WJplf/HspyMNBmqqfquDpxm+ZUWihNqAkVH5P21pZxvRBTrVD9N/LviAQcHNL/yA5eoJ8lC1hO3l71zi+3UtrJql3SyJRDdtwQGyOnAly0LOify5l11mY61NTSXwmj/p3RG/TgBrcEIH7H+fNoPTk0dnnnfEJcA1TcywX7H1qWguzD4EZASgWUawqclqvRPFbpxqDccBH2psdMGj9SrlJLK5lpmiyFpFq+D7bIasvzmrTuIXeNEuK8B1PufBlyHaPjEromO0mzI9kZg22N33iwu8sUw4o6KckgSXNDotUvSs6em2kGUUrnCKgNGVlkuKCM71Eby9m2OjaKx/ydDwaY02ZR33P91BHlnPKTtDWaFlKQ3Y9YCuMZRlpxTXDD2YYyw4umIb6gGX/jb0iHnhKs+OrxtELzUGFTYpkV/DTsZ2LY0e6sdNmjr6oQ/m+DF3JVhuzifw/QZOHYcodEZRuibdJp1unY09YrTELo+mZDYrfA7kQ+Eg=
