language: node_js
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    # $ travis encrypt $(heroku auth:token)
    # ›   Warning: token will expire 03/28/2019
    secure: jV09gyrmkIja73ghaxFVRhTGDntkI8alZd+l4tw7i4gxMyDWX+67eCWTUxGI4b+qUxqtnj4scecYL3YSX7zjkVeA9sLb9Sn5LWlIgJmjApu/xfteect/rNvmX91VSMU/mEPH2Z4NFmENDWyLI6p134Y8WammEepd7yG6CMug3+74hi6phCvzdZueYfZJnyY2qFRxV4DVdZ/AatIwRbvYMMRek//lgP9lchIGPoFzPrTzMdaJ8HgZ5GN++lIs2//s9T5ANMF2h8BLJcRK5z9h32gtbIwk+PncDnHdPd2liDWDHAvDOB2VzNcuukqeRZOSbE4Nk50Qu/cLhNwIFI3ZWbN0xHMM/jjeu18Lpa/Pw82zOTABo+yN1WaeZtdHEqFg5ft6npnXNJbLe510Xwqu2FgkwHtTQyY0CWstOuyphDMPPWzJxjNGnonMKkNCkVMgnQWOyVdZpnHJbNCOP1qoLAy0Ox2K9Adhbe6bq11H34czhcVhOhAMGTNGV/dv4XdTggIwDHojLS7LPhrgDYnvW1vtgER7YYZXQTFKACjNPa4qtFJuUj/h4LgbCjd8kP18KdoHxI2RrxuEIHMxClYc5QaVfdURTlkf/q2Uf7JwsX2FMIISh6OgGDth9FUuBmwZAKQzbjAZnR4V2l43tvQVHdXMNDdg3Cz0OZLfR2hZfgE=
  app: draftail-playground
  on:
    repo: thibaudcolas/draftail-playground
