language: node_js
notifications:
  email: false
  slack:
    rooms:
      secure: LLIuCOqOB0GLiyyV/L+NPErpAM4T3DuZQKa9v08R2nqQZ/53uUnNg25/4hzjnVoBNtJGrfdWKLjx4Ddgox4h97oD2aos8xLyuQXEp+S3rVPc02fTilU4HRrMoxbl4qzvAjhQlwSLaCva1xQJ9RRgTUkz22azt3MAkwe/eUtyUSq3A2BJi/pVBW0WJplf/HspyMNBmqqfquDpxm+ZUWihNqAkVH5P21pZxvRBTrVD9N/LviAQcHNL/yA5eoJ8lC1hO3l71zi+3UtrJql3SyJRDdtwQGyOnAly0LOify5l11mY61NTSXwmj/p3RG/TgBrcEIH7H+fNoPTk0dnnnfEJcA1TcywX7H1qWguzD4EZASgWUawqclqvRPFbpxqDccBH2psdMGj9SrlJLK5lpmiyFpFq+D7bIasvzmrTuIXeNEuK8B1PufBlyHaPjEromO0mzI9kZg22N33iwu8sUw4o6KckgSXNDotUvSs6em2kGUUrnCKgNGVlkuKCM71Eby9m2OjaKx/ydDwaY02ZR33P91BHlnPKTtDWaFlKQ3Y9YCuMZRlpxTXDD2YYyw4umIb6gGX/jb0iHnhKs+OrxtELzUGFTYpkV/DTsZ2LY0e6sdNmjr6oQ/m+DF3JVhuzifw/QZOHYcodEZRuibdJp1unY09YrTELo+mZDYrfA7kQ+Eg=
deploy:
  provider: heroku
  api_key:
    secure: BlcU++Qq/cUCfGANIMccurGCrqN0tXwbbIGt12oZdSPYI8oM99/ZAZFxv5yn/BgK1cD/HppcA9nR/SGq8MT/VcM7o9/pOuiL8yjYHPVwUVCUdKBWs4MqLThWKCTBnBwPdnOhYzx76cQLcwZr8xThVl2MA7MLcZ/rmxgAFHRGEci3430JpXxocdpGQEB1Up7BHLX4cCOfivgky/N5K8/2PBIcwADmLkjWPpT9UA2Rf9oraDjwy6UASEXlmpqoY0UZXjfUA0yPC2x/Z6rfZWl26xzruD0MB2iuYzuz5DhGsBYRybMCl5TDFsO+evn17+lVPaKlC+BVqk1wSkODngGun0QfNDImVfDin+eytpJhNYwQ17/gtTecbesMgEGakAkTV8SqoS3Sz52jsYbzt8s4RMY8cLrfIJKAa/H6uPo3g5bilqgMBi4pSIeUJ5rxflUvACnzRPOPva8kWF1k3bXG0fLq+nvowib/pdvi6TjGP0x0tCPY3fvxfn/juNlpDgqW4iUXvMLsfvVGzBCQTpmgQ1ZBBgOiBeeR4fnbOJTU5RdzPRPYKqHZBwpFZFCgNM8b1vh2TR/Xhx0RUo4FavaCpKeJQOYxnShonPTAGjpSFhCnB7dGgLvCfLFsb5R4YY2stJldfvyjPLqgMvHcbHfuaTxRRuZMjbbW3m0sMv19FPE=
  app: draftjs-exporter
  on:
    repo: springload/draftjs_exporter_demo
    branch: master
