language: node_js
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: dVV4DNsxhCP6uOu970Y6MgrSXiDLPjnsjpccQgkHkhIFZMpOkE+MHIhF7JF0ASRtw7vdlzCojotXnuqx2orNHtD3VrNz9MMFkeAtldTU+HF12IDf8OP9ChK05/roBSfQFSH48Z0myM0MC/Eeu6Zb+ia3571vXaUzYcOl5aJdAQzqzIdTfuY4Fh4IYvwYUJmyhDON3d7DtxbNhFP+rVmx8+dTX2hg0jhsz+IVaJc/06TuB42Z6EJtdRk/TD2Op42No3AZ7S6JgynHmAx+lVrnTTRa470Lf9QOXSRUS1IRHayfIB0++BMzwQYXd7QREwnRT9Hg7EVuTQvEe3nKbxikPPv6B8NOjYHrxwKejhXpV09DzjQLHq5gLrqVfLLFTnURLQ2+wxGXW9OCyu5gxu0gpb/trwJ4tIMkEeL+vE18yuCT42pv5uP6pSp3/8/Pe7B/15dNomtIw7UmpXU8Zxxo2ZNIwyHpZqwQfkCKfOVxYwmRJFcQh7ESU5JVpw1LVW6rPBbXHO1nosZnC5GFora9D4iEwvbH+J71Mbh7yjPMUnpOcKrVEdVgi0sWYvM1eD8KsHhRrDHAPZqXRsas1DoJwtzwTZj209YuCE6peCELppHPsKT0uUWGEVDcwY2LGxjqOjkBe17SCni1x42WZQgneFuzAya8oHoi36xcdhrTRJw=
  app: draftail-playground
  on:
    repo: thibaudcolas/draftail-playground
